### ISSUE TITLE
Permutations without repitation

### ISSUE THREAD

**Issue by bartwind** [drupol/phpermutations#13]
How to get permutations without repitations?
array(1,2,3,4,5,6)
all perms for 3: example: 1,2,3 1,2,4 etc

**Comment by drupol** [comment]
Hey hi!

Good question! I think this is not implemented.

You're looking for all the combinations of a given size right?

**Comment by drupol** [comment]
Have you tried this?

```php
<?php

declare(strict_types=1);

use drupol\phpermutations\Iterators\Combinations;

include 'vendor/autoload.php';

$input = [1,2,3,4,5,6];

var_dump(iterator_to_array(new Combinations($input, 3)));
```

**Comment by bartwind** [comment]
Yes bro but I need without repitations - and I need it with good performence because my input have 49 numbers and param is = 6 ;)

**Comment by bartwind** [comment]
So for example I need results with combinations without repitations so for example: 1,2,3  - but 3,2,1 (this one is worng because its repitation just other order with elements in array) - its called in Math permutations without repitations

**Comment by drupol** [comment]
Hi "bro", 

I gave you the solution up there, feel free to re-open the issue if it doesn't fit your needs.

**Comment by bartwind** [comment]
Hi 
thank you so much for help, I was using this package long time ago not right way :)

Regards

**Comment by drupol** [comment]
You're welcome!
